### PR TITLE
Logo rotate animation with css

### PR DESCRIPTION
**Pull request by vltansky**
cause why not :)
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline
https://codepen.io/vltansky/pen/wvLyYZX

### CODE REVIEW

**Comment by cocopon** [comment]
Thank you for your contribution, and sorry for the late reply...

I wasn’t aware of `animation-timeline: scroll()` feature. It looks useful, but it doesn’t work on some major browsers like Firefox and Safari. What do you think about this?

**Comment by vltansky** [comment]
I've added fallback

**Comment by cocopon** [comment]
Great! Could you run `npm run format` in `packages/tweakpane` directory to pass the CI check?

**Comment by cocopon** [comment]
Merged, thanks!

**Pull request merged**
